#General properties
set_property IOSTANDARD LVCMOS33 [get_ports]
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]

#Clock signal
set_property PACKAGE_PIN E3 [get_ports CLK]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK]

#Switches
set_property PACKAGE_PIN U9 [get_ports {SWITCHES[0]}]
set_property PACKAGE_PIN U8 [get_ports {SWITCHES[1]}]
set_property PACKAGE_PIN R7 [get_ports {SWITCHES[2]}]
set_property PACKAGE_PIN R6 [get_ports {SWITCHES[3]}]
set_property PACKAGE_PIN R5 [get_ports {SWITCHES[4]}]
set_property PACKAGE_PIN V7 [get_ports {SWITCHES[5]}]
set_property PACKAGE_PIN V6 [get_ports {SWITCHES[6]}]
set_property PACKAGE_PIN V5 [get_ports {SWITCHES[7]}]
set_property PACKAGE_PIN U4 [get_ports {SWITCHES[8]}]
set_property PACKAGE_PIN V2 [get_ports {SWITCHES[9]}]
set_property PACKAGE_PIN U2 [get_ports {SWITCHES[10]}]
set_property PACKAGE_PIN T3 [get_ports {SWITCHES[11]}]

#VGA Connector
set_property PACKAGE_PIN B7  [get_ports {RGB_OUT[0]}]
set_property PACKAGE_PIN C7  [get_ports {RGB_OUT[1]}]
set_property PACKAGE_PIN D7  [get_ports {RGB_OUT[2]}]
set_property PACKAGE_PIN D8  [get_ports {RGB_OUT[3]}]
set_property PACKAGE_PIN C6  [get_ports {RGB_OUT[4]}]
set_property PACKAGE_PIN A5  [get_ports {RGB_OUT[5]}]
set_property PACKAGE_PIN B6  [get_ports {RGB_OUT[6]}]
set_property PACKAGE_PIN A6  [get_ports {RGB_OUT[7]}]
set_property PACKAGE_PIN A3  [get_ports {RGB_OUT[8]}]
set_property PACKAGE_PIN B4  [get_ports {RGB_OUT[9]}]
set_property PACKAGE_PIN C5  [get_ports {RGB_OUT[10]}]
set_property PACKAGE_PIN A4  [get_ports {RGB_OUT[11]}]
set_property PACKAGE_PIN B11 [get_ports HSYNC_OUT]
set_property PACKAGE_PIN B12 [get_ports VSYNC_OUT]

#CellRam Control
set_property PACKAGE_PIN T15 [get_ports RamCLK]
set_property PACKAGE_PIN T13 [get_ports RamADVn]
set_property PACKAGE_PIN L18 [get_ports RamCEn]
set_property PACKAGE_PIN J14 [get_ports RamCRE]
set_property PACKAGE_PIN H14 [get_ports RamOEn]
set_property PACKAGE_PIN R11 [get_ports RamWEn]
set_property PACKAGE_PIN J15 [get_ports RamLBn]
set_property PACKAGE_PIN J13 [get_ports RamUBn]
set_property PACKAGE_PIN T14 [get_ports RamWait]

#CellRam Data
set_property PACKAGE_PIN R12 [get_ports {MemDB[0]}]
set_property PACKAGE_PIN T11 [get_ports {MemDB[1]}]
set_property PACKAGE_PIN U12 [get_ports {MemDB[2]}]
set_property PACKAGE_PIN R13 [get_ports {MemDB[3]}]
set_property PACKAGE_PIN U18 [get_ports {MemDB[4]}]
set_property PACKAGE_PIN R17 [get_ports {MemDB[5]}]
set_property PACKAGE_PIN T18 [get_ports {MemDB[6]}]
set_property PACKAGE_PIN R18 [get_ports {MemDB[7]}]
set_property PACKAGE_PIN F18 [get_ports {MemDB[8]}]
set_property PACKAGE_PIN G18 [get_ports {MemDB[9]}]
set_property PACKAGE_PIN G17 [get_ports {MemDB[10]}]
set_property PACKAGE_PIN M18 [get_ports {MemDB[11]}]
set_property PACKAGE_PIN M17 [get_ports {MemDB[12]}]
set_property PACKAGE_PIN P18 [get_ports {MemDB[13]}]
set_property PACKAGE_PIN N17 [get_ports {MemDB[14]}]
set_property PACKAGE_PIN P17 [get_ports {MemDB[15]}]

#CellRam Address
set_property PACKAGE_PIN J18 [get_ports {MemAdr[0]}]
set_property PACKAGE_PIN H17 [get_ports {MemAdr[1]}]
set_property PACKAGE_PIN H15 [get_ports {MemAdr[2]}]
set_property PACKAGE_PIN J17 [get_ports {MemAdr[3]}]
set_property PACKAGE_PIN H16 [get_ports {MemAdr[4]}]
set_property PACKAGE_PIN K15 [get_ports {MemAdr[5]}]
set_property PACKAGE_PIN K13 [get_ports {MemAdr[6]}]
set_property PACKAGE_PIN N15 [get_ports {MemAdr[7]}]
set_property PACKAGE_PIN V16 [get_ports {MemAdr[8]}]
set_property PACKAGE_PIN U14 [get_ports {MemAdr[9]}]
set_property PACKAGE_PIN V14 [get_ports {MemAdr[10]}]
set_property PACKAGE_PIN V12 [get_ports {MemAdr[11]}]
set_property PACKAGE_PIN P14 [get_ports {MemAdr[12]}]
set_property PACKAGE_PIN U16 [get_ports {MemAdr[13]}]
set_property PACKAGE_PIN R15 [get_ports {MemAdr[14]}]
set_property PACKAGE_PIN N14 [get_ports {MemAdr[15]}]
set_property PACKAGE_PIN N16 [get_ports {MemAdr[16]}]
set_property PACKAGE_PIN M13 [get_ports {MemAdr[17]}]
set_property PACKAGE_PIN V17 [get_ports {MemAdr[18]}]
set_property PACKAGE_PIN U17 [get_ports {MemAdr[19]}]
set_property PACKAGE_PIN T10 [get_ports {MemAdr[20]}]
set_property PACKAGE_PIN M16 [get_ports {MemAdr[21]}]
set_property PACKAGE_PIN U13 [get_ports {MemAdr[22]}]